### ISSUE TITLE
Is there any way to get frames out of the ffmpeg node?

### ISSUE THREAD

**Issue by Seba3Fi** [kevinGodell/node-red-contrib-ffmpeg-spawn#1]
Dear @kevinGodell , thanks for posting this module, I am testing it in the context of a home made security system (learning process)

My current workflow is something like this:
-In Scrypted the rstp flows are processed, and motion is detected. This triggers MQTT events that I receive on Node Red. Scrypted also provides some features like exposing to Apple HomeKit and others, and rebroadcasting camera traffic via rtsp.
-The second layer is Node Red. Today I am getting a picture from every camera via http, and procesing it with Tensorflow to detect objects of interst.

Instead of fetching images via http (that provides a lot of timeouts) I would rather use the rtsp stream to get 1 picture at a time via your ffmpeg node.

I have used ffmpeg from the command line, and it provides the frames, which I could save to disk or pipe into another ffmpeg command for further processing. But that leaves the image let's say at the operating system level, and I would rather have the image processed on node red.

Could you please expand the examples so that on e of the outputs shows 1 frame?

![WhatsApp Image 2023-04-14 at 11 21 43](https://user-images.githubusercontent.com/15160805/232071373-a2743f4b-cebb-4a44-b8fa-f309d09ab115.jpeg)

Thanks in advance,
Sebastián

**Comment by Seba3Fi** [comment]
Forgot to mention that I am not sure if this is the right way to ask for a favor, actually there is no issue with your software, it works fabulous. Thanks

**Comment by kevinGodell** [comment]
We can figure it out. Can you open a thread on the node-red forum and tag me there. Please also include what type of hardware you are running node-red and the versions and os. Thanks.

**Comment by Seba3Fi** [comment]
I think I have done it, thanks, let's close the thread here. Thanks!
